[package]
name = "harmony-ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "harmony_ffi"
crate-type = ["staticlib"]

[dependencies]
openai-harmony = { git = "https://github.com/openai/harmony" }
